/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cms;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kassem Tar
 */
public class AgenciesEditPanel extends javax.swing.JPanel {
     private static final Logger LOGGER = Logger.getLogger(AgenciesEditPanel.class.getName());
    /**
    /**
     * Creates new form AgenciesPanel
     */
    public AgenciesEditPanel() {
        initComponents();
    }
    
    public AgenciesEditPanel(String id) {
        initComponents();
        searchByIdTextField.setText(id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        searchByIdButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ridTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rphoneTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        searchByIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AnameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MnameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        represintiveTextField = new javax.swing.JTextField();

        setLayout(null);

        deleteButton.setText("حذف سجل");
        deleteButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton);
        deleteButton.setBounds(29, 385, 81, 20);

        saveButton.setText("حفظ سجل");
        saveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton);
        saveButton.setBounds(820, 380, 80, 20);

        searchByIdButton.setText("بحث عن");
        searchByIdButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchByIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIdButtonActionPerformed(evt);
            }
        });
        add(searchByIdButton);
        searchByIdButton.setBounds(820, 89, 80, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("الهيئات والمحاكم والنيابات");
        add(jLabel10);
        jLabel10.setBounds(365, 6, 363, 32);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("هاتف الهيئة");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5);
        jLabel5.setBounds(781, 184, 119, 18);
        add(phoneNumberTextField);
        phoneNumberTextField.setBounds(470, 182, 293, 30);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("رقم البطاقة الشخصية أو التعريف");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel7);
        jLabel7.setBounds(279, 184, 177, 18);
        add(ridTextField);
        ridTextField.setBounds(37, 182, 230, 30);

        jLabel8.setText("الهاتف المندوب \\نقال");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel8);
        jLabel8.setBounds(279, 231, 110, 18);
        add(rphoneTextField);
        rphoneTextField.setBounds(37, 229, 230, 40);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ملاحظات");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel9);
        jLabel9.setBounds(790, 240, 105, 18);

        noteTextArea.setColumns(20);
        noteTextArea.setRows(5);
        jScrollPane1.setViewportView(noteTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(440, 240, 320, 120);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("المعرف");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1);
        jLabel1.setBounds(671, 90, 59, 18);

        searchByIdTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(searchByIdTextField);
        searchByIdTextField.setBounds(582, 88, 71, 22);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("جهة التكليف");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2);
        jLabel2.setBounds(336, 90, 101, 18);

        AnameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(AnameTextField);
        AnameTextField.setBounds(32, 89, 286, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("أسم رئيس أو مدير الهيئة");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3);
        jLabel3.setBounds(781, 136, 119, 18);
        add(MnameTextField);
        MnameTextField.setBounds(423, 134, 340, 30);

        jLabel4.setText("أسم مندوب الهيئة");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel4);
        jLabel4.setBounds(279, 136, 100, 18);
        add(represintiveTextField);
        represintiveTextField.setBounds(37, 134, 230, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String id = searchByIdTextField.getText();
        String aName = AnameTextField.getText();
        String mName = MnameTextField.getText();
        String phoneNumber = phoneNumberTextField.getText();
        String represintive = represintiveTextField.getText();
        String rid = ridTextField.getText();
        String rphone = rphoneTextField.getText();
        String note = noteTextArea.getText();
        String query = "UPDATE `agencies` SET `A_name`=?, `M_name`=?, `phone_num`=?, `represintive`=?, `r_id`=?, `r_phone`=?, `notes`=? WHERE `id`=?";
        if(aName.isBlank() | mName.isBlank() | represintive.isBlank() | rid.isBlank()){
                String m = "الرجاء تأكد من البيانات يجب: تعبئة المهم منها!";
                JOptionPane.showMessageDialog(null, "error: " + m + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
        }else { 
            try{
                PreparedStatement pstmt = db.mycon().prepareStatement(query);
                pstmt.setString(1, aName);
                pstmt.setString(2, mName);
                pstmt.setString(3, phoneNumber);
                pstmt.setString(4, represintive);
                pstmt.setString(5, rid);
                pstmt.setString(6, rphone);
                pstmt.setString(7, note);
                pstmt.setString(8, id);
                pstmt.executeUpdate();

                pstmt.close();
            }catch(SQLException ex){
                LOGGER.log(Level.SEVERE, "An error occurred during login: {0}", ex);
                CmsLogger.log(ex.getMessage());
                JOptionPane.showMessageDialog(null, "error: " + ex.getMessage() + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void searchByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIdButtonActionPerformed
        // TODO add your handling code here:
        String id = searchByIdTextField.getText();
        if(id.isBlank()){
            String m = "الرجاء ادخال رقم المعرف";
            JOptionPane.showMessageDialog(null, "error: " + m + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
        }else{ 
            String query = "SELECT * FROM`agencies` WHERE `id`=?";
            try{
                PreparedStatement pstmt = db.mycon().prepareStatement(query);
                pstmt.setString(1, id);
                ResultSet rs = pstmt.executeQuery();

                if(rs.next()){
                    AnameTextField.setText(rs.getString("A_name"));
                    MnameTextField.setText(rs.getString("M_name"));
                    phoneNumberTextField.setText(rs.getString("phone_num"));
                    represintiveTextField.setText(rs.getString("represintive"));
                    ridTextField.setText(rs.getString("r_id"));
                    rphoneTextField.setText(rs.getString("r_phone"));
                    noteTextArea.setText(rs.getString("notes"));
                }
                rs.close();
                pstmt.close();
            }catch(SQLException ex){
                LOGGER.log(Level.SEVERE, "An error occurred during login: {0}", ex);
                CmsLogger.log(ex.getMessage());
                JOptionPane.showMessageDialog(null, "error: " + ex.getMessage() + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_searchByIdButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String id = searchByIdTextField.getText();
        String query = "DELETE FROM `agencies` WHERE `id`=?";
        if(id.isBlank()){
            String m = "الرجاء ادخال رقم المعرف المراد حذفه!";
            JOptionPane.showMessageDialog(null, "error: " + m + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
        }else{
            int option = JOptionPane.showConfirmDialog(null, "هل حق تريد حذف الهيئة؟", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                try{
                    PreparedStatement pstmt = db.mycon().prepareStatement(query);
                    pstmt.setString(1, id);
                    pstmt.executeUpdate();

                    pstmt.close();
                }catch(SQLException ex){
                    LOGGER.log(Level.SEVERE, "An error occurred during login: {0}", ex);
                    CmsLogger.log(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "error: " + ex.getMessage() + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                System.out.println("User clicked No");
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnameTextField;
    private javax.swing.JTextField MnameTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noteTextArea;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField represintiveTextField;
    private javax.swing.JTextField ridTextField;
    private javax.swing.JTextField rphoneTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchByIdButton;
    private javax.swing.JTextField searchByIdTextField;
    // End of variables declaration//GEN-END:variables
}
