/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cms;

import com.toedter.calendar.JDateChooser;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import report.methods.ReportView;

/**
 *
 * @author anas almograbi
 */
public class ExportAddpanal extends javax.swing.JFrame {

    /**
     * Creates new form ExportAddpanal
     */
    private static final Logger LOGGER = Logger.getLogger(ExportAddpanal.class.getName());
    private int id;
    public ExportAddpanal() {
       initComponents();
       this.setTitle("ExportAddpanal");
       this.setSize(500,420);
       this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.setLocationRelativeTo(null);
       this.setVisible(true); 
       this.setResizable(false);
       dataload();
    }
    
    ExportAddpanal(int id){
        this();
        this.id = id;
    }

    void dataload(){
        ArrayList<ResultSet> tables_db = db.dataload("import");
        ResultSet im = tables_db.get(0);
        
        try{
            Vector v = new Vector();
            
           //agencies combo box loadeer
           
            while(im.next()){
                v.add(im.getString("id"));
                DefaultComboBoxModel dc = new DefaultComboBoxModel(v);
                importComboBox.setModel(dc);
            }
  
           
            im.close();
            
        }catch(SQLException ex){
            LOGGER.log(Level.SEVERE, "An error occurred during login: {0}", ex);
            CmsLogger.log(ex.getMessage());
            JOptionPane.showMessageDialog(null, "error: " + ex.getMessage() + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        importComboBox = new javax.swing.JComboBox<>();
        exportDateChooser = new com.toedter.calendar.JDateChooser();
        saveButton = new javax.swing.JButton();
        eixtButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel2.setText("الرقم الفني :  ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        jLabel4.setText("رقم الصادر :  ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("الصادر");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(151, 6, 205, 36);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setText("تاريخ الصادر :  ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 210, 120, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel7.setText("الرقم الوارد  : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 110, 120, 30);
        getContentPane().add(importComboBox);
        importComboBox.setBounds(110, 110, 130, 30);
        getContentPane().add(exportDateChooser);
        exportDateChooser.setBounds(110, 210, 130, 30);

        saveButton.setBackground(new java.awt.Color(0, 0, 0));
        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("صادر جديد");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(350, 330, 120, 50);

        eixtButton.setBackground(new java.awt.Color(0, 0, 0));
        eixtButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eixtButton.setForeground(new java.awt.Color(255, 255, 255));
        eixtButton.setText("خروج");
        eixtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eixtButtonActionPerformed(evt);
            }
        });
        getContentPane().add(eixtButton);
        eixtButton.setBounds(40, 330, 120, 50);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 500, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String iid = importComboBox.getSelectedItem().toString();
        String sql = "INSERT INTO export (`i_id`, `date`) VALUES (?, ?)";
        
        try{
            SimpleDateFormat inputFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy", Locale.ENGLISH);
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
            String imdate = outputFormat.format(inputFormat.parse(exportDateChooser.getDate().toString()));
            PreparedStatement pstmt = db.mycon().prepareStatement(sql);
            pstmt.setString(1, iid);
            pstmt.setString(2, imdate);
            pstmt.executeUpdate();
            
            Statement stmt = db.mycon().createStatement();
            stmt.executeUpdate("UPDATE import SET state='منجزة' WHERE id='"+iid+"'");
            JOptionPane.showMessageDialog(null, "تم الحفظ!");
        }catch(SQLException | ParseException ex){
           LOGGER.log(Level.SEVERE, "An error occurred during login: {0}", ex);
            CmsLogger.log(ex.getMessage());
            JOptionPane.showMessageDialog(null, "error: " + ex.getMessage() + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void eixtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eixtButtonActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eixtButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportAddpanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportAddpanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportAddpanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportAddpanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportAddpanal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eixtButton;
    private com.toedter.calendar.JDateChooser exportDateChooser;
    private javax.swing.JComboBox<String> importComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
