package cms;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author intel
 */
public class Sigup_Panel extends javax.swing.JFrame {

    /**
     * 
     * @param password
     * @return 
     */
    private static final Logger LOGGER = Logger.getLogger(Login.class.getName());
    private boolean isPasswordValid(String password) {
        String regex = "^(?=.*[0-9])(?=\\S+$).{8,}$";
        // The regular expression for a strong password
        // At least 8 characters long (.{8,})
        // Contains at least one digit ((?=.*[0-9]))
        // Contains at least one special character from the set [@#$%^&+=] ((?=.*[@#$%^&+=]))
        // Does not contain any whitespace ((?=\\S+$))
        
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password);

        return matcher.matches();
    }
    
    public Sigup_Panel() {
        initComponents();
            this.setSize(270,295);
       this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.setLocationRelativeTo(null);
       this.setVisible(true); 
       this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reloToggleButton = new javax.swing.JToggleButton();
        userLabel = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        pass2Label = new javax.swing.JLabel();
        passField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        passField1 = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        pass2Label1 = new javax.swing.JLabel();
        showPasswordButton2 = new javax.swing.JToggleButton();
        showPasswordButton1 = new javax.swing.JToggleButton();
        passField1Label = new javax.swing.JLabel();
        passField2Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(278, 300));
        setMinimumSize(new java.awt.Dimension(278, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 330));
        getContentPane().setLayout(null);

        reloToggleButton.setForeground(new java.awt.Color(51, 51, 51));
        reloToggleButton.setText("موظف");
        reloToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloToggleButtonActionPerformed(evt);
            }
        });

        userLabel.setText("اسم المستخدم");

        passLabel.setText("كلمة المرور");

        pass2Label.setText("تأكيد كلمة المرور");

        passField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passField2FocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("تسجيل الموظفين الجدد");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 16));

        passField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passField1FocusLost(evt);
            }
        });

        registerButton.setText("التسجيل");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        exitButton.setText("الخروج");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        pass2Label1.setText("الدور");

        showPasswordButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/img/show.png"))); // NOI18N
        showPasswordButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordButton2ActionPerformed(evt);
            }
        });

        showPasswordButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/img/show.png"))); // NOI18N
        showPasswordButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordButton1ActionPerformed(evt);
            }
        });

        passField1Label.setText("...");

        passField2Label.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(showPasswordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passField1Label)
                                    .addComponent(passField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(userText))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reloToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pass2Label1)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(exitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(passField2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pass2Label)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(showPasswordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passField2Label))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passLabel)
                        .addComponent(passField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showPasswordButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pass2Label))
                    .addComponent(showPasswordButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass2Label1)
                    .addComponent(reloToggleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(exitButton))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 278, 463);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reloToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloToggleButtonActionPerformed
        // TODO add your handling code here:
        if(reloToggleButton.isSelected()){
            reloToggleButton.setText("مدير");
        }else {
            reloToggleButton.setText("موظف");
        }
    }//GEN-LAST:event_reloToggleButtonActionPerformed

    private void showPasswordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordButton2ActionPerformed
        // TODO add your handling code here:
        if(showPasswordButton2.isSelected()){
            passField2.setEchoChar((char)0);
            showPasswordButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/img/DnotShow.png")));
        }else {
            passField2.setEchoChar('*');
            showPasswordButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/img/show.png")));
        }
    }//GEN-LAST:event_showPasswordButton2ActionPerformed

    private void showPasswordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordButton1ActionPerformed
        // TODO add your handling code here:
        if(showPasswordButton1.isSelected()){
            passField1.setEchoChar((char)0);
            showPasswordButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/img/DnotShow.png")));
        }else {
            passField1.setEchoChar('*');
            showPasswordButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/img/show.png")));
        }
    }//GEN-LAST:event_showPasswordButton1ActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        String username = userText.getText();
        String password1 = String.valueOf(passField1.getPassword());
        String password2 = String.valueOf(passField2.getPassword());
        boolean isAdmin = reloToggleButton.isSelected();
        if(password1.equals(password2)){
            String sql = "INSERT INTO `user` (name, password, is_admin) VALUES (?, ?, ?)";
            try{
                PreparedStatement pstmt = db.mycon().prepareStatement(sql);
                pstmt.setString(1, username);
                pstmt.setString(2, password1);
                pstmt.setBoolean(3, isAdmin);
                pstmt.executeUpdate();
            }catch(SQLException ex){
                LOGGER.log(Level.SEVERE, "An error occurred during login: {0}", ex);
                CmsLogger.log(ex.getMessage());
                JOptionPane.showMessageDialog(null, "error: " + ex.getMessage() + "!", "خطأ!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void passField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField2FocusLost
        // TODO add your handling code here:
        String password1 = String.valueOf(passField1.getPassword());
        String password2 = String.valueOf(passField2.getPassword());
        
        if(password1.equals(password2)){
            passField2Label.setText("مطابقة");
            passField2Label.setForeground(Color.green);
        } else {
            passField2Label.setText("غير مطابقة");
            passField2Label.setForeground(Color.red);
        }
    }//GEN-LAST:event_passField2FocusLost

    private void passField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField1FocusLost
        // TODO add your handling code here:
        String password = String.valueOf(passField1.getPassword());
        if(isPasswordValid(password)){
            passField1Label.setText("مقبولة");
            passField1Label.setForeground(Color.green);
        }else{
            passField1Label.setText("ضعيفة");
            passField1Label.setForeground(Color.red);
        }
    }//GEN-LAST:event_passField1FocusLost

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sigup_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sigup_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sigup_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sigup_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sigup_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pass2Label;
    private javax.swing.JLabel pass2Label1;
    private javax.swing.JPasswordField passField1;
    private javax.swing.JLabel passField1Label;
    private javax.swing.JPasswordField passField2;
    private javax.swing.JLabel passField2Label;
    private javax.swing.JLabel passLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JToggleButton reloToggleButton;
    private javax.swing.JToggleButton showPasswordButton1;
    private javax.swing.JToggleButton showPasswordButton2;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
